package terminfo

// Code generated by gen.go. DO NOT EDIT.

const (
	// AutoLeftMargin indicates cub1 wraps from column 0 to last column.
	AutoLeftMargin = iota

	// AutoRightMargin indicates terminal has automatic margins.
	AutoRightMargin

	// NoEscCtlc indicates beehive (f1=escape, f2=ctrl C).
	NoEscCtlc

	// CeolStandoutGlitch indicates standout not erased by overwriting (hp).
	CeolStandoutGlitch

	// EatNewlineGlitch indicates newline ignored after 80 cols (concept).
	EatNewlineGlitch

	// EraseOverstrike indicates can erase overstrikes with a blank.
	EraseOverstrike

	// GenericType indicates generic line type.
	GenericType

	// HardCopy indicates hardcopy terminal.
	HardCopy

	// HasMetaKey indicates Has a meta key (i.e., sets 8th-bit).
	HasMetaKey

	// HasStatusLine indicates has extra status line.
	HasStatusLine

	// InsertNullGlitch indicates insert mode distinguishes nulls.
	InsertNullGlitch

	// MemoryAbove indicates display may be retained above the screen.
	MemoryAbove

	// MemoryBelow indicates display may be retained below the screen.
	MemoryBelow

	// MoveInsertMode indicates safe to move while in insert mode.
	MoveInsertMode

	// MoveStandoutMode indicates safe to move while in standout mode.
	MoveStandoutMode

	// OverStrike indicates terminal can overstrike.
	OverStrike

	// StatusLineEscOk indicates escape can be used on the status line.
	StatusLineEscOk

	// DestTabsMagicSmso indicates tabs destructive, magic so char (t1061).
	DestTabsMagicSmso

	// TildeGlitch indicates cannot print ~'s (Hazeltine).
	TildeGlitch

	// TransparentUnderline indicates underline character overstrikes.
	TransparentUnderline

	// XonXoff indicates terminal uses xon/xoff handshaking.
	XonXoff

	// NeedsXonXoff indicates padding will not work, xon/xoff required.
	NeedsXonXoff

	// PrtrSilent indicates printer will not echo on screen.
	PrtrSilent

	// HardCursor indicates cursor is hard to see.
	HardCursor

	// NonRevRmcup indicates smcup does not reverse rmcup.
	NonRevRmcup

	// NoPadChar indicates pad character does not exist.
	NoPadChar

	// NonDestScrollRegion indicates scrolling region is non-destructive.
	NonDestScrollRegion

	// CanChange indicates terminal can re-define existing colors.
	CanChange

	// BackColorErase indicates screen erased with background color.
	BackColorErase

	// HueLightnessSaturation indicates terminal uses only HLS color notation (Tektronix).
	HueLightnessSaturation

	// ColAddrGlitch indicates only positive motion for hpa/mhpa caps.
	ColAddrGlitch

	// CrCancelsMicroMode indicates using cr turns off micro mode.
	CrCancelsMicroMode

	// HasPrintWheel indicates printer needs operator to change character set.
	HasPrintWheel

	// RowAddrGlitch indicates only positive motion for vpa/mvpa caps.
	RowAddrGlitch

	// SemiAutoRightMargin indicates printing in last column causes cr.
	SemiAutoRightMargin

	// CpiChangesRes indicates changing character pitch changes resolution.
	CpiChangesRes

	// LpiChangesRes indicates changing line pitch changes resolution.
	LpiChangesRes

	// BackspacesWithBs indicates uses ^H to move left.
	BackspacesWithBs

	// CrtNoScrolling indicates crt cannot scroll.
	CrtNoScrolling

	// NoCorrectlyWorkingCr indicates no way to go to start of line.
	NoCorrectlyWorkingCr

	// GnuHasMetaKey indicates has meta key.
	GnuHasMetaKey

	// LinefeedIsNewline indicates move down with \n.
	LinefeedIsNewline

	// HasHardwareTabs indicates has 8-char tabs invoked with ^I.
	HasHardwareTabs

	// ReturnDoesClrEol indicates return clears the line.
	ReturnDoesClrEol
)

const (
	// Columns is number of columns in a line.
	Columns = iota

	// InitTabs is tabs initially every # spaces.
	InitTabs

	// Lines is number of lines on screen or page.
	Lines

	// LinesOfMemory is lines of memory if > line. 0 means varies.
	LinesOfMemory

	// MagicCookieGlitch is number of blank characters left by smso or rmso.
	MagicCookieGlitch

	// PaddingBaudRate is lowest baud rate where padding needed.
	PaddingBaudRate

	// VirtualTerminal is virtual terminal number (CB/unix).
	VirtualTerminal

	// WidthStatusLine is number of columns in status line.
	WidthStatusLine

	// NumLabels is number of labels on screen.
	NumLabels

	// LabelHeight is rows in each label.
	LabelHeight

	// LabelWidth is columns in each label.
	LabelWidth

	// MaxAttributes is maximum combined attributes terminal can handle.
	MaxAttributes

	// MaximumWindows is maximum number of definable windows.
	MaximumWindows

	// MaxColors is maximum number of colors on screen.
	MaxColors

	// MaxPairs is maximum number of color-pairs on the screen.
	MaxPairs

	// NoColorVideo is video attributes that cannot be used with colors.
	NoColorVideo

	// BufferCapacity is numbers of bytes buffered before printing.
	BufferCapacity

	// DotVertSpacing is spacing of pins vertically in pins per inch.
	DotVertSpacing

	// DotHorzSpacing is spacing of dots horizontally in dots per inch.
	DotHorzSpacing

	// MaxMicroAddress is maximum value in micro_..._address.
	MaxMicroAddress

	// MaxMicroJump is maximum value in parm_..._micro.
	MaxMicroJump

	// MicroColSize is character step size when in micro mode.
	MicroColSize

	// MicroLineSize is line step size when in micro mode.
	MicroLineSize

	// NumberOfPins is numbers of pins in print-head.
	NumberOfPins

	// OutputResChar is horizontal resolution in units per line.
	OutputResChar

	// OutputResLine is vertical resolution in units per line.
	OutputResLine

	// OutputResHorzInch is horizontal resolution in units per inch.
	OutputResHorzInch

	// OutputResVertInch is vertical resolution in units per inch.
	OutputResVertInch

	// PrintRate is print rate in characters per second.
	PrintRate

	// WideCharSize is character step size when in double wide mode.
	WideCharSize

	// Buttons is number of buttons on mouse.
	Buttons

	// BitImageEntwining is number of passes for each bit-image row.
	BitImageEntwining

	// BitImageType is type of bit-image device.
	BitImageType

	// MagicCookieGlitchUl is number of blanks left by ul.
	MagicCookieGlitchUl

	// CarriageReturnDelay is pad needed for CR.
	CarriageReturnDelay

	// NewLineDelay is pad needed for LF.
	NewLineDelay

	// BackspaceDelay is padding required for ^H.
	BackspaceDelay

	// HorizontalTabDelay is padding required for ^I.
	HorizontalTabDelay

	// NumberOfFunctionKeys is count of function keys.
	NumberOfFunctionKeys
)

const (
	// BackTab is the back tab (P).
	BackTab = iota

	// Bell is the audible signal (bell) (P).
	Bell

	// CarriageReturn is the carriage return (P*) (P*).
	CarriageReturn

	// ChangeScrollRegion is the change region to line #1 to line #2 (P).
	ChangeScrollRegion

	// ClearAllTabs is the clear all tab stops (P).
	ClearAllTabs

	// ClearScreen is the clear screen and home cursor (P*).
	ClearScreen

	// ClrEol is the clear to end of line (P).
	ClrEol

	// ClrEos is the clear to end of screen (P*).
	ClrEos

	// ColumnAddress is the horizontal position #1, absolute (P).
	ColumnAddress

	// CommandCharacter is the terminal settable cmd character in prototype !?.
	CommandCharacter

	// CursorAddress is the move to row #1 columns #2.
	CursorAddress

	// CursorDown is the down one line.
	CursorDown

	// CursorHome is the home cursor (if no cup).
	CursorHome

	// CursorInvisible is the make cursor invisible.
	CursorInvisible

	// CursorLeft is the move left one space.
	CursorLeft

	// CursorMemAddress is the memory relative cursor addressing, move to row #1 columns #2.
	CursorMemAddress

	// CursorNormal is the make cursor appear normal (undo civis/cvvis).
	CursorNormal

	// CursorRight is the non-destructive space (move right one space).
	CursorRight

	// CursorToLl is the last line, first column (if no cup).
	CursorToLl

	// CursorUp is the up one line.
	CursorUp

	// CursorVisible is the make cursor very visible.
	CursorVisible

	// DeleteCharacter is the delete character (P*).
	DeleteCharacter

	// DeleteLine is the delete line (P*).
	DeleteLine

	// DisStatusLine is the disable status line.
	DisStatusLine

	// DownHalfLine is the half a line down.
	DownHalfLine

	// EnterAltCharsetMode is the start alternate character set (P).
	EnterAltCharsetMode

	// EnterBlinkMode is the turn on blinking.
	EnterBlinkMode

	// EnterBoldMode is the turn on bold (extra bright) mode.
	EnterBoldMode

	// EnterCaMode is the string to start programs using cup.
	EnterCaMode

	// EnterDeleteMode is the enter delete mode.
	EnterDeleteMode

	// EnterDimMode is the turn on half-bright mode.
	EnterDimMode

	// EnterInsertMode is the enter insert mode.
	EnterInsertMode

	// EnterSecureMode is the turn on blank mode (characters invisible).
	EnterSecureMode

	// EnterProtectedMode is the turn on protected mode.
	EnterProtectedMode

	// EnterReverseMode is the turn on reverse video mode.
	EnterReverseMode

	// EnterStandoutMode is the begin standout mode.
	EnterStandoutMode

	// EnterUnderlineMode is the begin underline mode.
	EnterUnderlineMode

	// EraseChars is the erase #1 characters (P).
	EraseChars

	// ExitAltCharsetMode is the end alternate character set (P).
	ExitAltCharsetMode

	// ExitAttributeMode is the turn off all attributes.
	ExitAttributeMode

	// ExitCaMode is the strings to end programs using cup.
	ExitCaMode

	// ExitDeleteMode is the end delete mode.
	ExitDeleteMode

	// ExitInsertMode is the exit insert mode.
	ExitInsertMode

	// ExitStandoutMode is the exit standout mode.
	ExitStandoutMode

	// ExitUnderlineMode is the exit underline mode.
	ExitUnderlineMode

	// FlashScreen is the visible bell (may not move cursor).
	FlashScreen

	// FormFeed is the hardcopy terminal page eject (P*).
	FormFeed

	// FromStatusLine is the return from status line.
	FromStatusLine

	// Init1string is the initialization string.
	Init1string

	// Init2string is the initialization string.
	Init2string

	// Init3string is the initialization string.
	Init3string

	// InitFile is the name of initialization file.
	InitFile

	// InsertCharacter is the insert character (P).
	InsertCharacter

	// InsertLine is the insert line (P*).
	InsertLine

	// InsertPadding is the insert padding after inserted character.
	InsertPadding

	// KeyBackspace is the backspace key.
	KeyBackspace

	// KeyCatab is the clear-all-tabs key.
	KeyCatab

	// KeyClear is the clear-screen or erase key.
	KeyClear

	// KeyCtab is the clear-tab key.
	KeyCtab

	// KeyDc is the delete-character key.
	KeyDc

	// KeyDl is the delete-line key.
	KeyDl

	// KeyDown is the down-arrow key.
	KeyDown

	// KeyEic is the sent by rmir or smir in insert mode.
	KeyEic

	// KeyEol is the clear-to-end-of-line key.
	KeyEol

	// KeyEos is the clear-to-end-of-screen key.
	KeyEos

	// KeyF0 is the F0 function key.
	KeyF0

	// KeyF1 is the F1 function key.
	KeyF1

	// KeyF10 is the F10 function key.
	KeyF10

	// KeyF2 is the F2 function key.
	KeyF2

	// KeyF3 is the F3 function key.
	KeyF3

	// KeyF4 is the F4 function key.
	KeyF4

	// KeyF5 is the F5 function key.
	KeyF5

	// KeyF6 is the F6 function key.
	KeyF6

	// KeyF7 is the F7 function key.
	KeyF7

	// KeyF8 is the F8 function key.
	KeyF8

	// KeyF9 is the F9 function key.
	KeyF9

	// KeyHome is the home key.
	KeyHome

	// KeyIc is the insert-character key.
	KeyIc

	// KeyIl is the insert-line key.
	KeyIl

	// KeyLeft is the left-arrow key.
	KeyLeft

	// KeyLl is the lower-left key (home down).
	KeyLl

	// KeyNpage is the next-page key.
	KeyNpage

	// KeyPpage is the previous-page key.
	KeyPpage

	// KeyRight is the right-arrow key.
	KeyRight

	// KeySf is the scroll-forward key.
	KeySf

	// KeySr is the scroll-backward key.
	KeySr

	// KeyStab is the set-tab key.
	KeyStab

	// KeyUp is the up-arrow key.
	KeyUp

	// KeypadLocal is the leave 'keyboard_transmit' mode.
	KeypadLocal

	// KeypadXmit is the enter 'keyboard_transmit' mode.
	KeypadXmit

	// LabF0 is the label on function key f0 if not f0.
	LabF0

	// LabF1 is the label on function key f1 if not f1.
	LabF1

	// LabF10 is the label on function key f10 if not f10.
	LabF10

	// LabF2 is the label on function key f2 if not f2.
	LabF2

	// LabF3 is the label on function key f3 if not f3.
	LabF3

	// LabF4 is the label on function key f4 if not f4.
	LabF4

	// LabF5 is the label on function key f5 if not f5.
	LabF5

	// LabF6 is the label on function key f6 if not f6.
	LabF6

	// LabF7 is the label on function key f7 if not f7.
	LabF7

	// LabF8 is the label on function key f8 if not f8.
	LabF8

	// LabF9 is the label on function key f9 if not f9.
	LabF9

	// MetaOff is the turn off meta mode.
	MetaOff

	// MetaOn is the turn on meta mode (8th-bit on).
	MetaOn

	// Newline is the newline (behave like cr followed by lf).
	Newline

	// PadChar is the padding char (instead of null).
	PadChar

	// ParmDch is the delete #1 characters (P*).
	ParmDch

	// ParmDeleteLine is the delete #1 lines (P*).
	ParmDeleteLine

	// ParmDownCursor is the down #1 lines (P*).
	ParmDownCursor

	// ParmIch is the insert #1 characters (P*).
	ParmIch

	// ParmIndex is the scroll forward #1 lines (P).
	ParmIndex

	// ParmInsertLine is the insert #1 lines (P*).
	ParmInsertLine

	// ParmLeftCursor is the move #1 characters to the left (P).
	ParmLeftCursor

	// ParmRightCursor is the move #1 characters to the right (P*).
	ParmRightCursor

	// ParmRindex is the scroll back #1 lines (P).
	ParmRindex

	// ParmUpCursor is the up #1 lines (P*).
	ParmUpCursor

	// PkeyKey is the program function key #1 to type string #2.
	PkeyKey

	// PkeyLocal is the program function key #1 to execute string #2.
	PkeyLocal

	// PkeyXmit is the program function key #1 to transmit string #2.
	PkeyXmit

	// PrintScreen is the print contents of screen.
	PrintScreen

	// PrtrOff is the turn off printer.
	PrtrOff

	// PrtrOn is the turn on printer.
	PrtrOn

	// RepeatChar is the repeat char #1 #2 times (P*).
	RepeatChar

	// Reset1string is the reset string.
	Reset1string

	// Reset2string is the reset string.
	Reset2string

	// Reset3string is the reset string.
	Reset3string

	// ResetFile is the name of reset file.
	ResetFile

	// RestoreCursor is the restore cursor to position of last save_cursor.
	RestoreCursor

	// RowAddress is the vertical position #1 absolute (P).
	RowAddress

	// SaveCursor is the save current cursor position (P).
	SaveCursor

	// ScrollForward is the scroll text up (P).
	ScrollForward

	// ScrollReverse is the scroll text down (P).
	ScrollReverse

	// SetAttributes is the define video attributes #1-#9 (PG9).
	SetAttributes

	// SetTab is the set a tab in every row, current columns.
	SetTab

	// SetWindow is the current window is lines #1-#2 cols #3-#4.
	SetWindow

	// Tab is the tab to next 8-space hardware tab stop.
	Tab

	// ToStatusLine is the move to status line, column #1.
	ToStatusLine

	// UnderlineChar is the underline char and move past it.
	UnderlineChar

	// UpHalfLine is the half a line up.
	UpHalfLine

	// InitProg is the path name of program for initialization.
	InitProg

	// KeyA1 is the upper left of keypad.
	KeyA1

	// KeyA3 is the upper right of keypad.
	KeyA3

	// KeyB2 is the center of keypad.
	KeyB2

	// KeyC1 is the lower left of keypad.
	KeyC1

	// KeyC3 is the lower right of keypad.
	KeyC3

	// PrtrNon is the turn on printer for #1 bytes.
	PrtrNon

	// CharPadding is the like ip but when in insert mode.
	CharPadding

	// AcsChars is the graphics charset pairs, based on vt100.
	AcsChars

	// PlabNorm is the program label #1 to show string #2.
	PlabNorm

	// KeyBtab is the back-tab key.
	KeyBtab

	// EnterXonMode is the turn on xon/xoff handshaking.
	EnterXonMode

	// ExitXonMode is the turn off xon/xoff handshaking.
	ExitXonMode

	// EnterAmMode is the turn on automatic margins.
	EnterAmMode

	// ExitAmMode is the turn off automatic margins.
	ExitAmMode

	// XonCharacter is the XON character.
	XonCharacter

	// XoffCharacter is the XOFF character.
	XoffCharacter

	// EnaAcs is the enable alternate char set.
	EnaAcs

	// LabelOn is the turn on soft labels.
	LabelOn

	// LabelOff is the turn off soft labels.
	LabelOff

	// KeyBeg is the begin key.
	KeyBeg

	// KeyCancel is the cancel key.
	KeyCancel

	// KeyClose is the close key.
	KeyClose

	// KeyCommand is the command key.
	KeyCommand

	// KeyCopy is the copy key.
	KeyCopy

	// KeyCreate is the create key.
	KeyCreate

	// KeyEnd is the end key.
	KeyEnd

	// KeyEnter is the enter/send key.
	KeyEnter

	// KeyExit is the exit key.
	KeyExit

	// KeyFind is the find key.
	KeyFind

	// KeyHelp is the help key.
	KeyHelp

	// KeyMark is the mark key.
	KeyMark

	// KeyMessage is the message key.
	KeyMessage

	// KeyMove is the move key.
	KeyMove

	// KeyNext is the next key.
	KeyNext

	// KeyOpen is the open key.
	KeyOpen

	// KeyOptions is the options key.
	KeyOptions

	// KeyPrevious is the previous key.
	KeyPrevious

	// KeyPrint is the print key.
	KeyPrint

	// KeyRedo is the redo key.
	KeyRedo

	// KeyReference is the reference key.
	KeyReference

	// KeyRefresh is the refresh key.
	KeyRefresh

	// KeyReplace is the replace key.
	KeyReplace

	// KeyRestart is the restart key.
	KeyRestart

	// KeyResume is the resume key.
	KeyResume

	// KeySave is the save key.
	KeySave

	// KeySuspend is the suspend key.
	KeySuspend

	// KeyUndo is the undo key.
	KeyUndo

	// KeySbeg is the shifted begin key.
	KeySbeg

	// KeyScancel is the shifted cancel key.
	KeyScancel

	// KeyScommand is the shifted command key.
	KeyScommand

	// KeyScopy is the shifted copy key.
	KeyScopy

	// KeyScreate is the shifted create key.
	KeyScreate

	// KeySdc is the shifted delete-character key.
	KeySdc

	// KeySdl is the shifted delete-line key.
	KeySdl

	// KeySelect is the select key.
	KeySelect

	// KeySend is the shifted end key.
	KeySend

	// KeySeol is the shifted clear-to-end-of-line key.
	KeySeol

	// KeySexit is the shifted exit key.
	KeySexit

	// KeySfind is the shifted find key.
	KeySfind

	// KeyShelp is the shifted help key.
	KeyShelp

	// KeyShome is the shifted home key.
	KeyShome

	// KeySic is the shifted insert-character key.
	KeySic

	// KeySleft is the shifted left-arrow key.
	KeySleft

	// KeySmessage is the shifted message key.
	KeySmessage

	// KeySmove is the shifted move key.
	KeySmove

	// KeySnext is the shifted next key.
	KeySnext

	// KeySoptions is the shifted options key.
	KeySoptions

	// KeySprevious is the shifted previous key.
	KeySprevious

	// KeySprint is the shifted print key.
	KeySprint

	// KeySredo is the shifted redo key.
	KeySredo

	// KeySreplace is the shifted replace key.
	KeySreplace

	// KeySright is the shifted right-arrow key.
	KeySright

	// KeySrsume is the shifted resume key.
	KeySrsume

	// KeySsave is the shifted save key.
	KeySsave

	// KeySsuspend is the shifted suspend key.
	KeySsuspend

	// KeySundo is the shifted undo key.
	KeySundo

	// ReqForInput is the send next input char (for ptys).
	ReqForInput

	// KeyF11 is the F11 function key.
	KeyF11

	// KeyF12 is the F12 function key.
	KeyF12

	// KeyF13 is the F13 function key.
	KeyF13

	// KeyF14 is the F14 function key.
	KeyF14

	// KeyF15 is the F15 function key.
	KeyF15

	// KeyF16 is the F16 function key.
	KeyF16

	// KeyF17 is the F17 function key.
	KeyF17

	// KeyF18 is the F18 function key.
	KeyF18

	// KeyF19 is the F19 function key.
	KeyF19

	// KeyF20 is the F20 function key.
	KeyF20

	// KeyF21 is the F21 function key.
	KeyF21

	// KeyF22 is the F22 function key.
	KeyF22

	// KeyF23 is the F23 function key.
	KeyF23

	// KeyF24 is the F24 function key.
	KeyF24

	// KeyF25 is the F25 function key.
	KeyF25

	// KeyF26 is the F26 function key.
	KeyF26

	// KeyF27 is the F27 function key.
	KeyF27

	// KeyF28 is the F28 function key.
	KeyF28

	// KeyF29 is the F29 function key.
	KeyF29

	// KeyF30 is the F30 function key.
	KeyF30

	// KeyF31 is the F31 function key.
	KeyF31

	// KeyF32 is the F32 function key.
	KeyF32

	// KeyF33 is the F33 function key.
	KeyF33

	// KeyF34 is the F34 function key.
	KeyF34

	// KeyF35 is the F35 function key.
	KeyF35

	// KeyF36 is the F36 function key.
	KeyF36

	// KeyF37 is the F37 function key.
	KeyF37

	// KeyF38 is the F38 function key.
	KeyF38

	// KeyF39 is the F39 function key.
	KeyF39

	// KeyF40 is the F40 function key.
	KeyF40

	// KeyF41 is the F41 function key.
	KeyF41

	// KeyF42 is the F42 function key.
	KeyF42

	// KeyF43 is the F43 function key.
	KeyF43

	// KeyF44 is the F44 function key.
	KeyF44

	// KeyF45 is the F45 function key.
	KeyF45

	// KeyF46 is the F46 function key.
	KeyF46

	// KeyF47 is the F47 function key.
	KeyF47

	// KeyF48 is the F48 function key.
	KeyF48

	// KeyF49 is the F49 function key.
	KeyF49

	// KeyF50 is the F50 function key.
	KeyF50

	// KeyF51 is the F51 function key.
	KeyF51

	// KeyF52 is the F52 function key.
	KeyF52

	// KeyF53 is the F53 function key.
	KeyF53

	// KeyF54 is the F54 function key.
	KeyF54

	// KeyF55 is the F55 function key.
	KeyF55

	// KeyF56 is the F56 function key.
	KeyF56

	// KeyF57 is the F57 function key.
	KeyF57

	// KeyF58 is the F58 function key.
	KeyF58

	// KeyF59 is the F59 function key.
	KeyF59

	// KeyF60 is the F60 function key.
	KeyF60

	// KeyF61 is the F61 function key.
	KeyF61

	// KeyF62 is the F62 function key.
	KeyF62

	// KeyF63 is the F63 function key.
	KeyF63

	// ClrBol is the Clear to beginning of line.
	ClrBol

	// ClearMargins is the clear right and left soft margins.
	ClearMargins

	// SetLeftMargin is the set left soft margin at current column.	 See smgl. (ML is not in BSD termcap).
	SetLeftMargin

	// SetRightMargin is the set right soft margin at current column.
	SetRightMargin

	// LabelFormat is the label format.
	LabelFormat

	// SetClock is the set clock, #1 hrs #2 mins #3 secs.
	SetClock

	// DisplayClock is the display clock.
	DisplayClock

	// RemoveClock is the remove clock.
	RemoveClock

	// CreateWindow is the define a window #1 from #2,#3 to #4,#5.
	CreateWindow

	// GotoWindow is the go to window #1.
	GotoWindow

	// Hangup is the hang-up phone.
	Hangup

	// DialPhone is the dial number #1.
	DialPhone

	// QuickDial is the dial number #1 without checking.
	QuickDial

	// Tone is the select touch tone dialing.
	Tone

	// Pulse is the select pulse dialing.
	Pulse

	// FlashHook is the flash switch hook.
	FlashHook

	// FixedPause is the pause for 2-3 seconds.
	FixedPause

	// WaitTone is the wait for dial-tone.
	WaitTone

	// User0 is the User string #0.
	User0

	// User1 is the User string #1.
	User1

	// User2 is the User string #2.
	User2

	// User3 is the User string #3.
	User3

	// User4 is the User string #4.
	User4

	// User5 is the User string #5.
	User5

	// User6 is the User string #6.
	User6

	// User7 is the User string #7.
	User7

	// User8 is the User string #8.
	User8

	// User9 is the User string #9.
	User9

	// OrigPair is the Set default pair to its original value.
	OrigPair

	// OrigColors is the Set all color pairs to the original ones.
	OrigColors

	// InitializeColor is the initialize color #1 to (#2,#3,#4).
	InitializeColor

	// InitializePair is the Initialize color pair #1 to fg=(#2,#3,#4), bg=(#5,#6,#7).
	InitializePair

	// SetColorPair is the Set current color pair to #1.
	SetColorPair

	// SetForeground is the Set foreground color #1.
	SetForeground

	// SetBackground is the Set background color #1.
	SetBackground

	// ChangeCharPitch is the Change number of characters per inch to #1.
	ChangeCharPitch

	// ChangeLinePitch is the Change number of lines per inch to #1.
	ChangeLinePitch

	// ChangeResHorz is the Change horizontal resolution to #1.
	ChangeResHorz

	// ChangeResVert is the Change vertical resolution to #1.
	ChangeResVert

	// DefineChar is the Define a character #1, #2 dots wide, descender #3.
	DefineChar

	// EnterDoublewideMode is the Enter double-wide mode.
	EnterDoublewideMode

	// EnterDraftQuality is the Enter draft-quality mode.
	EnterDraftQuality

	// EnterItalicsMode is the Enter italic mode.
	EnterItalicsMode

	// EnterLeftwardMode is the Start leftward carriage motion.
	EnterLeftwardMode

	// EnterMicroMode is the Start micro-motion mode.
	EnterMicroMode

	// EnterNearLetterQuality is the Enter NLQ mode.
	EnterNearLetterQuality

	// EnterNormalQuality is the Enter normal-quality mode.
	EnterNormalQuality

	// EnterShadowMode is the Enter shadow-print mode.
	EnterShadowMode

	// EnterSubscriptMode is the Enter subscript mode.
	EnterSubscriptMode

	// EnterSuperscriptMode is the Enter superscript mode.
	EnterSuperscriptMode

	// EnterUpwardMode is the Start upward carriage motion.
	EnterUpwardMode

	// ExitDoublewideMode is the End double-wide mode.
	ExitDoublewideMode

	// ExitItalicsMode is the End italic mode.
	ExitItalicsMode

	// ExitLeftwardMode is the End left-motion mode.
	ExitLeftwardMode

	// ExitMicroMode is the End micro-motion mode.
	ExitMicroMode

	// ExitShadowMode is the End shadow-print mode.
	ExitShadowMode

	// ExitSubscriptMode is the End subscript mode.
	ExitSubscriptMode

	// ExitSuperscriptMode is the End superscript mode.
	ExitSuperscriptMode

	// ExitUpwardMode is the End reverse character motion.
	ExitUpwardMode

	// MicroColumnAddress is the Like column_address in micro mode.
	MicroColumnAddress

	// MicroDown is the Like cursor_down in micro mode.
	MicroDown

	// MicroLeft is the Like cursor_left in micro mode.
	MicroLeft

	// MicroRight is the Like cursor_right in micro mode.
	MicroRight

	// MicroRowAddress is the Like row_address #1 in micro mode.
	MicroRowAddress

	// MicroUp is the Like cursor_up in micro mode.
	MicroUp

	// OrderOfPins is the Match software bits to print-head pins.
	OrderOfPins

	// ParmDownMicro is the Like parm_down_cursor in micro mode.
	ParmDownMicro

	// ParmLeftMicro is the Like parm_left_cursor in micro mode.
	ParmLeftMicro

	// ParmRightMicro is the Like parm_right_cursor in micro mode.
	ParmRightMicro

	// ParmUpMicro is the Like parm_up_cursor in micro mode.
	ParmUpMicro

	// SelectCharSet is the Select character set, #1.
	SelectCharSet

	// SetBottomMargin is the Set bottom margin at current line.
	SetBottomMargin

	// SetBottomMarginParm is the Set bottom margin at line #1 or (if smgtp is not given) #2 lines from bottom.
	SetBottomMarginParm

	// SetLeftMarginParm is the Set left (right) margin at column #1.
	SetLeftMarginParm

	// SetRightMarginParm is the Set right margin at column #1.
	SetRightMarginParm

	// SetTopMargin is the Set top margin at current line.
	SetTopMargin

	// SetTopMarginParm is the Set top (bottom) margin at row #1.
	SetTopMarginParm

	// StartBitImage is the Start printing bit image graphics.
	StartBitImage

	// StartCharSetDef is the Start character set definition #1, with #2 characters in the set.
	StartCharSetDef

	// StopBitImage is the Stop printing bit image graphics.
	StopBitImage

	// StopCharSetDef is the End definition of character set #1.
	StopCharSetDef

	// SubscriptCharacters is the List of subscriptable characters.
	SubscriptCharacters

	// SuperscriptCharacters is the List of superscriptable characters.
	SuperscriptCharacters

	// TheseCauseCr is the Printing any of these characters causes CR.
	TheseCauseCr

	// ZeroMotion is the No motion for subsequent character.
	ZeroMotion

	// CharSetNames is the Produce #1'th item from list of character set names.
	CharSetNames

	// KeyMouse is the Mouse event has occurred.
	KeyMouse

	// MouseInfo is the Mouse status information.
	MouseInfo

	// ReqMousePos is the Request mouse position.
	ReqMousePos

	// GetMouse is the Curses should get button events, parameter #1 not documented.
	GetMouse

	// SetAForeground is the Set foreground color to #1, using ANSI escape.
	SetAForeground

	// SetABackground is the Set background color to #1, using ANSI escape.
	SetABackground

	// PkeyPlab is the Program function key #1 to type string #2 and show string #3.
	PkeyPlab

	// DeviceType is the Indicate language/codeset support.
	DeviceType

	// CodeSetInit is the Init sequence for multiple codesets.
	CodeSetInit

	// Set0DesSeq is the Shift to codeset 0 (EUC set 0, ASCII).
	Set0DesSeq

	// Set1DesSeq is the Shift to codeset 1.
	Set1DesSeq

	// Set2DesSeq is the Shift to codeset 2.
	Set2DesSeq

	// Set3DesSeq is the Shift to codeset 3.
	Set3DesSeq

	// SetLrMargin is the Set both left and right margins to #1, #2.  (ML is not in BSD termcap).
	SetLrMargin

	// SetTbMargin is the Sets both top and bottom margins to #1, #2.
	SetTbMargin

	// BitImageRepeat is the Repeat bit image cell #1 #2 times.
	BitImageRepeat

	// BitImageNewline is the Move to next row of the bit image.
	BitImageNewline

	// BitImageCarriageReturn is the Move to beginning of same row.
	BitImageCarriageReturn

	// ColorNames is the Give name for color #1.
	ColorNames

	// DefineBitImageRegion is the Define rectangular bit image region.
	DefineBitImageRegion

	// EndBitImageRegion is the End a bit-image region.
	EndBitImageRegion

	// SetColorBand is the Change to ribbon color #1.
	SetColorBand

	// SetPageLength is the Set page length to #1 lines.
	SetPageLength

	// DisplayPcChar is the Display PC character #1.
	DisplayPcChar

	// EnterPcCharsetMode is the Enter PC character display mode.
	EnterPcCharsetMode

	// ExitPcCharsetMode is the Exit PC character display mode.
	ExitPcCharsetMode

	// EnterScancodeMode is the Enter PC scancode mode.
	EnterScancodeMode

	// ExitScancodeMode is the Exit PC scancode mode.
	ExitScancodeMode

	// PcTermOptions is the PC terminal options.
	PcTermOptions

	// ScancodeEscape is the Escape for scancode emulation.
	ScancodeEscape

	// AltScancodeEsc is the Alternate escape for scancode emulation.
	AltScancodeEsc

	// EnterHorizontalHlMode is the Enter horizontal highlight mode.
	EnterHorizontalHlMode

	// EnterLeftHlMode is the Enter left highlight mode.
	EnterLeftHlMode

	// EnterLowHlMode is the Enter low highlight mode.
	EnterLowHlMode

	// EnterRightHlMode is the Enter right highlight mode.
	EnterRightHlMode

	// EnterTopHlMode is the Enter top highlight mode.
	EnterTopHlMode

	// EnterVerticalHlMode is the Enter vertical highlight mode.
	EnterVerticalHlMode

	// SetAAttributes is the Define second set of video attributes #1-#6.
	SetAAttributes

	// SetPglenInch is the Set page length to #1 hundredth of an inch (some implementations use sL for termcap).
	SetPglenInch

	// TermcapInit2 is the secondary initialization string.
	TermcapInit2

	// TermcapReset is the terminal reset string.
	TermcapReset

	// LinefeedIfNotLf is the use to move down.
	LinefeedIfNotLf

	// BackspaceIfNotBs is the move left, if not ^H.
	BackspaceIfNotBs

	// OtherNonFunctionKeys is the list of self-mapped keycaps.
	OtherNonFunctionKeys

	// ArrowKeyMap is the map arrow keys rogue(1) motion keys.
	ArrowKeyMap

	// AcsUlcorner is the single upper left.
	AcsUlcorner

	// AcsLlcorner is the single lower left.
	AcsLlcorner

	// AcsUrcorner is the single upper right.
	AcsUrcorner

	// AcsLrcorner is the single lower right.
	AcsLrcorner

	// AcsLtee is the tee pointing right.
	AcsLtee

	// AcsRtee is the tee pointing left.
	AcsRtee

	// AcsBtee is the tee pointing up.
	AcsBtee

	// AcsTtee is the tee pointing down.
	AcsTtee

	// AcsHline is the single horizontal line.
	AcsHline

	// AcsVline is the single vertical line.
	AcsVline

	// AcsPlus is the single intersection.
	AcsPlus

	// MemoryLock is the lock memory above cursor.
	MemoryLock

	// MemoryUnlock is the unlock memory.
	MemoryUnlock

	// BoxChars1 is the box characters primary set.
	BoxChars1
)

const (
	CapCountBool   = ReturnDoesClrEol + 1
	CapCountNum    = NumberOfFunctionKeys + 1
	CapCountString = BoxChars1 + 1
)

// boolCapNames are the bool term cap names.
var boolCapNames = [...]string{
	"auto_left_margin", "bw",
	"auto_right_margin", "am",
	"no_esc_ctlc", "xsb",
	"ceol_standout_glitch", "xhp",
	"eat_newline_glitch", "xenl",
	"erase_overstrike", "eo",
	"generic_type", "gn",
	"hard_copy", "hc",
	"has_meta_key", "km",
	"has_status_line", "hs",
	"insert_null_glitch", "in",
	"memory_above", "da",
	"memory_below", "db",
	"move_insert_mode", "mir",
	"move_standout_mode", "msgr",
	"over_strike", "os",
	"status_line_esc_ok", "eslok",
	"dest_tabs_magic_smso", "xt",
	"tilde_glitch", "hz",
	"transparent_underline", "ul",
	"xon_xoff", "xon",
	"needs_xon_xoff", "nxon",
	"prtr_silent", "mc5i",
	"hard_cursor", "chts",
	"non_rev_rmcup", "nrrmc",
	"no_pad_char", "npc",
	"non_dest_scroll_region", "ndscr",
	"can_change", "ccc",
	"back_color_erase", "bce",
	"hue_lightness_saturation", "hls",
	"col_addr_glitch", "xhpa",
	"cr_cancels_micro_mode", "crxm",
	"has_print_wheel", "daisy",
	"row_addr_glitch", "xvpa",
	"semi_auto_right_margin", "sam",
	"cpi_changes_res", "cpix",
	"lpi_changes_res", "lpix",
	"backspaces_with_bs", "OTbs",
	"crt_no_scrolling", "OTns",
	"no_correctly_working_cr", "OTnc",
	"gnu_has_meta_key", "OTMT",
	"linefeed_is_newline", "OTNL",
	"has_hardware_tabs", "OTpt",
	"return_does_clr_eol", "OTxr",
}

// numCapNames are the num term cap names.
var numCapNames = [...]string{
	"columns", "cols",
	"init_tabs", "it",
	"lines", "lines",
	"lines_of_memory", "lm",
	"magic_cookie_glitch", "xmc",
	"padding_baud_rate", "pb",
	"virtual_terminal", "vt",
	"width_status_line", "wsl",
	"num_labels", "nlab",
	"label_height", "lh",
	"label_width", "lw",
	"max_attributes", "ma",
	"maximum_windows", "wnum",
	"max_colors", "colors",
	"max_pairs", "pairs",
	"no_color_video", "ncv",
	"buffer_capacity", "bufsz",
	"dot_vert_spacing", "spinv",
	"dot_horz_spacing", "spinh",
	"max_micro_address", "maddr",
	"max_micro_jump", "mjump",
	"micro_col_size", "mcs",
	"micro_line_size", "mls",
	"number_of_pins", "npins",
	"output_res_char", "orc",
	"output_res_line", "orl",
	"output_res_horz_inch", "orhi",
	"output_res_vert_inch", "orvi",
	"print_rate", "cps",
	"wide_char_size", "widcs",
	"buttons", "btns",
	"bit_image_entwining", "bitwin",
	"bit_image_type", "bitype",
	"magic_cookie_glitch_ul", "OTug",
	"carriage_return_delay", "OTdC",
	"new_line_delay", "OTdN",
	"backspace_delay", "OTdB",
	"horizontal_tab_delay", "OTdT",
	"number_of_function_keys", "OTkn",
}

// stringCapNames are the string term cap names.
var stringCapNames = [...]string{
	"back_tab", "cbt",
	"bell", "bel",
	"carriage_return", "cr",
	"change_scroll_region", "csr",
	"clear_all_tabs", "tbc",
	"clear_screen", "clear",
	"clr_eol", "el",
	"clr_eos", "ed",
	"column_address", "hpa",
	"command_character", "cmdch",
	"cursor_address", "cup",
	"cursor_down", "cud1",
	"cursor_home", "home",
	"cursor_invisible", "civis",
	"cursor_left", "cub1",
	"cursor_mem_address", "mrcup",
	"cursor_normal", "cnorm",
	"cursor_right", "cuf1",
	"cursor_to_ll", "ll",
	"cursor_up", "cuu1",
	"cursor_visible", "cvvis",
	"delete_character", "dch1",
	"delete_line", "dl1",
	"dis_status_line", "dsl",
	"down_half_line", "hd",
	"enter_alt_charset_mode", "smacs",
	"enter_blink_mode", "blink",
	"enter_bold_mode", "bold",
	"enter_ca_mode", "smcup",
	"enter_delete_mode", "smdc",
	"enter_dim_mode", "dim",
	"enter_insert_mode", "smir",
	"enter_secure_mode", "invis",
	"enter_protected_mode", "prot",
	"enter_reverse_mode", "rev",
	"enter_standout_mode", "smso",
	"enter_underline_mode", "smul",
	"erase_chars", "ech",
	"exit_alt_charset_mode", "rmacs",
	"exit_attribute_mode", "sgr0",
	"exit_ca_mode", "rmcup",
	"exit_delete_mode", "rmdc",
	"exit_insert_mode", "rmir",
	"exit_standout_mode", "rmso",
	"exit_underline_mode", "rmul",
	"flash_screen", "flash",
	"form_feed", "ff",
	"from_status_line", "fsl",
	"init_1string", "is1",
	"init_2string", "is2",
	"init_3string", "is3",
	"init_file", "if",
	"insert_character", "ich1",
	"insert_line", "il1",
	"insert_padding", "ip",
	"key_backspace", "kbs",
	"key_catab", "ktbc",
	"key_clear", "kclr",
	"key_ctab", "kctab",
	"key_dc", "kdch1",
	"key_dl", "kdl1",
	"key_down", "kcud1",
	"key_eic", "krmir",
	"key_eol", "kel",
	"key_eos", "ked",
	"key_f0", "kf0",
	"key_f1", "kf1",
	"key_f10", "kf10",
	"key_f2", "kf2",
	"key_f3", "kf3",
	"key_f4", "kf4",
	"key_f5", "kf5",
	"key_f6", "kf6",
	"key_f7", "kf7",
	"key_f8", "kf8",
	"key_f9", "kf9",
	"key_home", "khome",
	"key_ic", "kich1",
	"key_il", "kil1",
	"key_left", "kcub1",
	"key_ll", "kll",
	"key_npage", "knp",
	"key_ppage", "kpp",
	"key_right", "kcuf1",
	"key_sf", "kind",
	"key_sr", "kri",
	"key_stab", "khts",
	"key_up", "kcuu1",
	"keypad_local", "rmkx",
	"keypad_xmit", "smkx",
	"lab_f0", "lf0",
	"lab_f1", "lf1",
	"lab_f10", "lf10",
	"lab_f2", "lf2",
	"lab_f3", "lf3",
	"lab_f4", "lf4",
	"lab_f5", "lf5",
	"lab_f6", "lf6",
	"lab_f7", "lf7",
	"lab_f8", "lf8",
	"lab_f9", "lf9",
	"meta_off", "rmm",
	"meta_on", "smm",
	"newline", "nel",
	"pad_char", "pad",
	"parm_dch", "dch",
	"parm_delete_line", "dl",
	"parm_down_cursor", "cud",
	"parm_ich", "ich",
	"parm_index", "indn",
	"parm_insert_line", "il",
	"parm_left_cursor", "cub",
	"parm_right_cursor", "cuf",
	"parm_rindex", "rin",
	"parm_up_cursor", "cuu",
	"pkey_key", "pfkey",
	"pkey_local", "pfloc",
	"pkey_xmit", "pfx",
	"print_screen", "mc0",
	"prtr_off", "mc4",
	"prtr_on", "mc5",
	"repeat_char", "rep",
	"reset_1string", "rs1",
	"reset_2string", "rs2",
	"reset_3string", "rs3",
	"reset_file", "rf",
	"restore_cursor", "rc",
	"row_address", "vpa",
	"save_cursor", "sc",
	"scroll_forward", "ind",
	"scroll_reverse", "ri",
	"set_attributes", "sgr",
	"set_tab", "hts",
	"set_window", "wind",
	"tab", "ht",
	"to_status_line", "tsl",
	"underline_char", "uc",
	"up_half_line", "hu",
	"init_prog", "iprog",
	"key_a1", "ka1",
	"key_a3", "ka3",
	"key_b2", "kb2",
	"key_c1", "kc1",
	"key_c3", "kc3",
	"prtr_non", "mc5p",
	"char_padding", "rmp",
	"acs_chars", "acsc",
	"plab_norm", "pln",
	"key_btab", "kcbt",
	"enter_xon_mode", "smxon",
	"exit_xon_mode", "rmxon",
	"enter_am_mode", "smam",
	"exit_am_mode", "rmam",
	"xon_character", "xonc",
	"xoff_character", "xoffc",
	"ena_acs", "enacs",
	"label_on", "smln",
	"label_off", "rmln",
	"key_beg", "kbeg",
	"key_cancel", "kcan",
	"key_close", "kclo",
	"key_command", "kcmd",
	"key_copy", "kcpy",
	"key_create", "kcrt",
	"key_end", "kend",
	"key_enter", "kent",
	"key_exit", "kext",
	"key_find", "kfnd",
	"key_help", "khlp",
	"key_mark", "kmrk",
	"key_message", "kmsg",
	"key_move", "kmov",
	"key_next", "knxt",
	"key_open", "kopn",
	"key_options", "kopt",
	"key_previous", "kprv",
	"key_print", "kprt",
	"key_redo", "krdo",
	"key_reference", "kref",
	"key_refresh", "krfr",
	"key_replace", "krpl",
	"key_restart", "krst",
	"key_resume", "kres",
	"key_save", "ksav",
	"key_suspend", "kspd",
	"key_undo", "kund",
	"key_sbeg", "kBEG",
	"key_scancel", "kCAN",
	"key_scommand", "kCMD",
	"key_scopy", "kCPY",
	"key_screate", "kCRT",
	"key_sdc", "kDC",
	"key_sdl", "kDL",
	"key_select", "kslt",
	"key_send", "kEND",
	"key_seol", "kEOL",
	"key_sexit", "kEXT",
	"key_sfind", "kFND",
	"key_shelp", "kHLP",
	"key_shome", "kHOM",
	"key_sic", "kIC",
	"key_sleft", "kLFT",
	"key_smessage", "kMSG",
	"key_smove", "kMOV",
	"key_snext", "kNXT",
	"key_soptions", "kOPT",
	"key_sprevious", "kPRV",
	"key_sprint", "kPRT",
	"key_sredo", "kRDO",
	"key_sreplace", "kRPL",
	"key_sright", "kRIT",
	"key_srsume", "kRES",
	"key_ssave", "kSAV",
	"key_ssuspend", "kSPD",
	"key_sundo", "kUND",
	"req_for_input", "rfi",
	"key_f11", "kf11",
	"key_f12", "kf12",
	"key_f13", "kf13",
	"key_f14", "kf14",
	"key_f15", "kf15",
	"key_f16", "kf16",
	"key_f17", "kf17",
	"key_f18", "kf18",
	"key_f19", "kf19",
	"key_f20", "kf20",
	"key_f21", "kf21",
	"key_f22", "kf22",
	"key_f23", "kf23",
	"key_f24", "kf24",
	"key_f25", "kf25",
	"key_f26", "kf26",
	"key_f27", "kf27",
	"key_f28", "kf28",
	"key_f29", "kf29",
	"key_f30", "kf30",
	"key_f31", "kf31",
	"key_f32", "kf32",
	"key_f33", "kf33",
	"key_f34", "kf34",
	"key_f35", "kf35",
	"key_f36", "kf36",
	"key_f37", "kf37",
	"key_f38", "kf38",
	"key_f39", "kf39",
	"key_f40", "kf40",
	"key_f41", "kf41",
	"key_f42", "kf42",
	"key_f43", "kf43",
	"key_f44", "kf44",
	"key_f45", "kf45",
	"key_f46", "kf46",
	"key_f47", "kf47",
	"key_f48", "kf48",
	"key_f49", "kf49",
	"key_f50", "kf50",
	"key_f51", "kf51",
	"key_f52", "kf52",
	"key_f53", "kf53",
	"key_f54", "kf54",
	"key_f55", "kf55",
	"key_f56", "kf56",
	"key_f57", "kf57",
	"key_f58", "kf58",
	"key_f59", "kf59",
	"key_f60", "kf60",
	"key_f61", "kf61",
	"key_f62", "kf62",
	"key_f63", "kf63",
	"clr_bol", "el1",
	"clear_margins", "mgc",
	"set_left_margin", "smgl",
	"set_right_margin", "smgr",
	"label_format", "fln",
	"set_clock", "sclk",
	"display_clock", "dclk",
	"remove_clock", "rmclk",
	"create_window", "cwin",
	"goto_window", "wingo",
	"hangup", "hup",
	"dial_phone", "dial",
	"quick_dial", "qdial",
	"tone", "tone",
	"pulse", "pulse",
	"flash_hook", "hook",
	"fixed_pause", "pause",
	"wait_tone", "wait",
	"user0", "u0",
	"user1", "u1",
	"user2", "u2",
	"user3", "u3",
	"user4", "u4",
	"user5", "u5",
	"user6", "u6",
	"user7", "u7",
	"user8", "u8",
	"user9", "u9",
	"orig_pair", "op",
	"orig_colors", "oc",
	"initialize_color", "initc",
	"initialize_pair", "initp",
	"set_color_pair", "scp",
	"set_foreground", "setf",
	"set_background", "setb",
	"change_char_pitch", "cpi",
	"change_line_pitch", "lpi",
	"change_res_horz", "chr",
	"change_res_vert", "cvr",
	"define_char", "defc",
	"enter_doublewide_mode", "swidm",
	"enter_draft_quality", "sdrfq",
	"enter_italics_mode", "sitm",
	"enter_leftward_mode", "slm",
	"enter_micro_mode", "smicm",
	"enter_near_letter_quality", "snlq",
	"enter_normal_quality", "snrmq",
	"enter_shadow_mode", "sshm",
	"enter_subscript_mode", "ssubm",
	"enter_superscript_mode", "ssupm",
	"enter_upward_mode", "sum",
	"exit_doublewide_mode", "rwidm",
	"exit_italics_mode", "ritm",
	"exit_leftward_mode", "rlm",
	"exit_micro_mode", "rmicm",
	"exit_shadow_mode", "rshm",
	"exit_subscript_mode", "rsubm",
	"exit_superscript_mode", "rsupm",
	"exit_upward_mode", "rum",
	"micro_column_address", "mhpa",
	"micro_down", "mcud1",
	"micro_left", "mcub1",
	"micro_right", "mcuf1",
	"micro_row_address", "mvpa",
	"micro_up", "mcuu1",
	"order_of_pins", "porder",
	"parm_down_micro", "mcud",
	"parm_left_micro", "mcub",
	"parm_right_micro", "mcuf",
	"parm_up_micro", "mcuu",
	"select_char_set", "scs",
	"set_bottom_margin", "smgb",
	"set_bottom_margin_parm", "smgbp",
	"set_left_margin_parm", "smglp",
	"set_right_margin_parm", "smgrp",
	"set_top_margin", "smgt",
	"set_top_margin_parm", "smgtp",
	"start_bit_image", "sbim",
	"start_char_set_def", "scsd",
	"stop_bit_image", "rbim",
	"stop_char_set_def", "rcsd",
	"subscript_characters", "subcs",
	"superscript_characters", "supcs",
	"these_cause_cr", "docr",
	"zero_motion", "zerom",
	"char_set_names", "csnm",
	"key_mouse", "kmous",
	"mouse_info", "minfo",
	"req_mouse_pos", "reqmp",
	"get_mouse", "getm",
	"set_a_foreground", "setaf",
	"set_a_background", "setab",
	"pkey_plab", "pfxl",
	"device_type", "devt",
	"code_set_init", "csin",
	"set0_des_seq", "s0ds",
	"set1_des_seq", "s1ds",
	"set2_des_seq", "s2ds",
	"set3_des_seq", "s3ds",
	"set_lr_margin", "smglr",
	"set_tb_margin", "smgtb",
	"bit_image_repeat", "birep",
	"bit_image_newline", "binel",
	"bit_image_carriage_return", "bicr",
	"color_names", "colornm",
	"define_bit_image_region", "defbi",
	"end_bit_image_region", "endbi",
	"set_color_band", "setcolor",
	"set_page_length", "slines",
	"display_pc_char", "dispc",
	"enter_pc_charset_mode", "smpch",
	"exit_pc_charset_mode", "rmpch",
	"enter_scancode_mode", "smsc",
	"exit_scancode_mode", "rmsc",
	"pc_term_options", "pctrm",
	"scancode_escape", "scesc",
	"alt_scancode_esc", "scesa",
	"enter_horizontal_hl_mode", "ehhlm",
	"enter_left_hl_mode", "elhlm",
	"enter_low_hl_mode", "elohlm",
	"enter_right_hl_mode", "erhlm",
	"enter_top_hl_mode", "ethlm",
	"enter_vertical_hl_mode", "evhlm",
	"set_a_attributes", "sgr1",
	"set_pglen_inch", "slength",
	"termcap_init2", "OTi2",
	"termcap_reset", "OTrs",
	"linefeed_if_not_lf", "OTnl",
	"backspace_if_not_bs", "OTbc",
	"other_non_function_keys", "OTko",
	"arrow_key_map", "OTma",
	"acs_ulcorner", "OTG2",
	"acs_llcorner", "OTG3",
	"acs_urcorner", "OTG1",
	"acs_lrcorner", "OTG4",
	"acs_ltee", "OTGR",
	"acs_rtee", "OTGL",
	"acs_btee", "OTGU",
	"acs_ttee", "OTGD",
	"acs_hline", "OTGH",
	"acs_vline", "OTGV",
	"acs_plus", "OTGC",
	"memory_lock", "meml",
	"memory_unlock", "memu",
	"box_chars_1", "box1",
}
